SELECT * WHERE {
  ?s <http://purl.org/goodrelations/includes> ?o .
  BIND(<http://example.org/rowid>(?s,<http://purl.org/goodrelations/includes>,?o) as ?statement)
  ?statement <http://purl.org/goodrelations/includes> ?a
}
